kind: Service
apiVersion: v1
metadata:
  name: travel-agency-service
#  namespace: travel-agency-service   命名空間
spec:
  selector:
    app: travel-agency-service
  ports:
  - protocol: TCP
    port: 8083
    nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-service
#  namespace: travel-agency-service
spec:
  selector:
      matchLabels:
        app: travel-agency-service
  replicas: 2
  template:
    metadata:
#      namespace: travel-agency-service
      labels:
        app: travel-agency-service
    spec:
      containers:
        - name: travel-agency-service
          image: travel-agency-service:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8083
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password