apiVersion: v1
kind: ConfigMap
metadata:
  name: client-service
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.properties: |-
    bean.message=Testing reload ! Message from backend is: %s <br/> Services : %s

